### ISSUE TITLE
NSURLErrorDomain: Unsupported URL

### ISSUE THREAD

**Issue by muuvmuuv** [capacitor-community/http#33] opened 2020-07-09 16:42 UTC
**Describe the bug**

I am transforming our services to this native solution ATM and everything works fine except the [transloco language module](https://ngneat.github.io/transloco/docs/hack/#the-loader) which seems to only work with Angular HTTP Client. If I am changing the loader to native HTTP I get the following error from Xcode:

```
2020-07-09 18:33:56.457867+0200 App[51816:1435020] Task <25F642A2-F3D3-4215-B364-B443A1F2AB7A>.<5> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x6000034fa550 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=/languages/de-DE.json?, NSErrorFailingURLKey=/languages/de-DE.json?, NSLocalizedDescription=unsupported URL}
ERROR MESSAGE:  {"message":"Error","errorMessage":"unsupported URL","code":"GET"}
```

**To Reproduce**

I am going to add one if the above error is not clear enough.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I guess that it just has issues with getting local files so maybe it needs a prefix or something like `file://`.

**Comment by thomasvidas** [comment] 2021-03-24 18:10
Closing this since there is no reproduction (and it is very old). If its still an issue with the latest alpha, feel free to re-open 😄

**Closed by thomasvidas** 2021-03-24 18:10 UTC

**Comment by muuvmuuv** [comment] 2021-03-24 18:47
Will put it on my to-do to test that issue. If it's fixed with v3 than GG our app will be fully native HTTP. *-*
