### ISSUE TITLE
Can't get cookies on iOS

### ISSUE THREAD

**Issue by simonluebker** [capacitor-community/http#47] opened 2020-08-27 12:04 UTC
# Question
I'm here because of the wkwebview issue of getting and setting cookies and hoped that this plugin will resolve this problems. 
So i tried the Http.getCookie({url: ....}) method but the result is every time an empty array.

The first request to an IDP is done via an other framework so not with the Http Plugin. The IDP is setting the cookie. But it is not seen in Developer Console with Chrome when debugging on mobile. The cookie is seen when hosting the app in real browser but there also the plugins Http.GetCookie method returns an empty array.

So my Question is how to receive Cookies from other websites and send them with request to the same website?

I hope you can help me

**Comment by mlynch** [comment] 2020-09-17 15:42
Just making sure you're awaiting the promise?

It's possible the cookies are "sandboxed" somehow. Would need to dig in but if anyone else has ideas please chime in

**Comment by smoosh911** [comment] 2020-12-09 17:31
I have this same issue. 

Here are my dependencies:
    "@capacitor-community/http": "^0.2.1",
    "@capacitor/core": "^2.1.0",
    "@capacitor/ios": "^2.4.4",

The code I'm using:

    const cook1 = await Http.setCookie({
      url: '/',
      key: '_ga_F1R0Z1HBV5',
      value: 'GS1.1.1607469233.18.1.1607469258.0'
    });

    const cook2 = await Http.setCookie({
      url: '/',
      key: '_ga',
      value: 'GA1.1.172759051.1550597580'
    });

    const cook3 = await Http.setCookie({
      url: '/',
      key: 'dogy',
      value: 'dog world'
    });

    const getCookies = async () => {
      const ret = await Http.getCookies({
        url: '/'
      });
      console.log('Got cookies', ret);
      return JSON.stringify(ret.value);
    };

    const result = await getCookies();

    console.log('getCookies :>> ', result);

From what I can tell there are no errors, it simply doesn't work. I've tried on the device and on the simulator.

**Comment by dwieeb** [comment] 2020-12-09 18:19
@tafelnl Is this an issue [your implementation](https://github.com/ionic-team/capacitor/issues/1373#issuecomment-707822708) would fix?

**Comment by tafelnl** [comment] 2020-12-10 10:47
Well, yes and no. It's complicated and I am not a native developer. But I will do my best to explain:

## Android vs iOS

First of all we have to distinguish between Android and iOS.

On Android everything works just fine with one caveat:

> Android cookies will work just fine as long as you have your webview server running on http://localhost and you have your backend hosted on a secure (SSL) endpoint. There is a little bug with the persisting of cookies when you close the app quickly after booting up. But there is a simple fix available. See: #3012

On iOS cookies do not work at all or not correctly (dependent on your setup and use).

Therefore we the rest of this comment considers iOS.

## Client vs Server side

Next we need to distinguish between client side and server side cookies.

In an ideal world cookies would work as follows:

Client side cookies can be set by: `document.cookie = 'somecookie=yummy;'`. And you can get them by `const cookies = document.cookie`.

Server side cookies will be set by making use of Headers:
E.g.: `Set-Cookie: <cookie-name>=<cookie-value>; Domain=<domain-value>; Secure; HttpOnly`

If you use the flag `HttpOnly;`, you will not be able to get and use them from JavaScript. Otherwise you will also be able to get these cookies by running `const cookies = document.cookie`.

Now, as we know, cookies unfortunately do not behave like this on iOS. This is probably because of the fact that a custom scheme is used (`capacitor://`).

So the next step is to discover how they exactly _do_ behave.

## When do _Client_ side cookies work on iOS?

The answer is quite simple: _never_.

It's easy to reproduce this. Try running  `document.cookie = 'somecookie=yummy;'; const cookies = document.cookie;`. And you will see that `cookies` has a value of `""`. (see: https://github.com/ionic-team/capacitor/issues/1373#issuecomment-477969557)

## When do _Server_ side cookies work on iOS?

When you have your app configured as follows:
```
  "server": {
    "url": "http://example.com"
  }
```
It will work exactly the same as if you would visit http://example.com in Safari on your Mac or iPhone.

But since such a configuration is only for development purposes you config would probably look like this:

```
  "server": {}
```

This configuration makes your app launch from `capacitor://localhost`. But the URL's you will be calling from for example the `fetch` API, will probably be just a 'normal' URL (e.g.: https://example.com). Now, normally (like on Android with their http://localhost), this wouldn't be a problem. Just as long as you set the right flags (`Secure` and `SameSite=None`) (see also: https://github.com/ionic-team/capacitor/issues/3418#issuecomment-706159729).

But (understandably) iOS does not consider `capacitor://localhost` to be a Secure Context. And it is not likely that they will accept this sometime in the future. So therefore all URLs called from within that `capacitor://localhost` will not be able to set cookies.

What is remarkable is that iframes that are secure (e.g.: https://tr.snapchat.com for tracking) within the webview also seem to be considered insecure by iOS. Because they are also not able to retrieve cookies through a `fetch` request.

So how to fix all of this?

## How to fix the _Client_ side cookies on iOS?

This is pretty straight forward. As explained in my other comment (https://github.com/ionic-team/capacitor/issues/1373#issuecomment-707822708) we will have to proxy the `document.cookie`. This way we can override the normal behaviour of the setter and getter. The only thing that is needed for that fix to be implemented is a synchronous way to call native API's. See my feature request here: https://github.com/ionic-team/capacitor/issues/3675.

So not to worry about client side cookies, they can be fixed pretty easily.

## How to fix the _Server_ side cookies on iOS?

On to Server side cookies.

Again I am not a native developer. But I did some digging and came up with a few ideas.

The most straight forward (and also the worst) solution is by using a config similar to the following:
```
  "server": {
    "hostname": "subdomain.example.com"
  }
```
With `subdomain.example.com` being your _main_ domain used for API calls and Authentication. Somehow this tricks the WKWebView into thinking that it is running on `https://subdomain.example.com` (as far as I understand at least). This way cookies from `https://subdomain.example.com` are accepted. But all other cookies from other domains are still ignored.

This is of course not a viable solution in any way. It has many defects and use cases where this is not a working fix.

So what to do now?

I've got some (still vague) ideas about how to fix this:

A possible solution would be to add afterhooks to both the `XMLHttpRequest` and `fetch` API's. In those afterhooks you then read out all the cookie headers and finally set them manually by calling (the fixed) `document.cookie = `. This is almost perfect (besides the fact that it is hacky in my opinion). Only cookies with the `HttpOnly;` flag set will not be fixed with this (as JavaScript does not have access to them).

Another solution would be to add beforehooks to both the `XMLHttpRequest` and `fetch` API's. In those beforehooks you redirect all them requests to the `Capacitor.Plugins.Http` API. This would be very nice, but also very tricky. There are a lot of variables to be considered. And the `Plugins.Http` API might not be able to support all of them.

Last solution I had in mind, was to intercept all `XMLHttpRequest` and `fetch` calls _within_ the WKWebView. But I'm not sure if that would be possible. If it's possible, I think this would by far be the best solution; no weird hacky proxies for the JavaScript API's; just one simple interceptor in the native Swift code to read out all the cookie headers and set them in a way that they can be read out again by JavaScript.


Also worth noting is that the Cordova community is bothered by the same issues. A lot of information can be found there. See for example this library: https://github.com/CWBudde/cordova-plugin-wkwebview-inject-cookie. Although I do not understand what problem this library is trying to solve in what way exactly. It might be worth looking at.

**Comment by maartenmensink** [comment] 2021-01-21 14:52
Is there any update on this topic. Or is Set-Cookie a lost cause for iOs?

**Comment by thomasvidas** [comment] 2021-02-12 17:26
I'm closing this issue for now because this is mainly [an issue with Capacitor Core](https://github.com/ionic-team/capacitor/issues/1373). The team is aware and actively working on solutions, but for now it is outside the scope of this plugin due to limitations set by Apple with Third Party cookies

**Comment by thomasvidas** [comment] 2021-02-12 17:28
On second thought, I'll leave it open, but label it appropriately

**Comment by thomasvidas** [comment] 2021-05-26 01:56
This is fixed as best as it can be in this plugin. The issue is open in core, but with the recent 1.0 release of this plugin you can [specify the domains you need cookies from](https://github.com/capacitor-community/http#third-party-cookies-on-ios) and it may fit your use case.

Alternatively you can change the `hostname` in your capacitor config to allow your cookies to become first party cookies, but as we state in [the Capacitor config dogs](https://capacitorjs.com/docs/config), it is recommended to keep that value as `localhost` as it allows the use of Web APIs that would otherwise require a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) such as [`navigator.geolocation`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation) and [`MediaDevices.getUserMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).

**Closed by thomasvidas** 2021-05-26 01:56 UTC
Labels: On Hold
