### ISSUE TITLE
Timeout Values Working?

### ISSUE THREAD

**Issue by philbairsm** [capacitor-community/http#206] opened 2021-12-08 17:13 UTC
I have set the timeout values to an extremely low number (like .0001) to try to force a timeout. But the request does not timeout even though the response time was as high as two seconds. Are the timeout values being applied?

**Comment by thomasvidas** [comment] 2021-12-08 19:33
The value for `connectTimeout` should be a whole number value in milliseconds. On Android, if you pass a `float` it will be rounded up or down. If you pass a `0` value it will use the default values for the request handler.

The values are being applied [here on Android](https://github.com/capacitor-community/http/blob/3aca516560653349bd6f563b0d6c668e20827e03/android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java#L383) and [here in iOS](https://github.com/capacitor-community/http/blob/3aca516560653349bd6f563b0d6c668e20827e03/ios/Plugin/HttpRequestHandler.swift#L174).

Closing this unless you have a small reproduction of your issue since I'm not able to reproduce it.

**Closed by thomasvidas** 2021-12-08 19:33 UTC
