### ISSUE TITLE
get, post, put , patch and del methods throw UNIMPLEMENTED on android platform

### ISSUE THREAD

**Issue by tdesmet** [capacitor-community/http#127] opened 2021-05-28 08:51 UTC
**Describe the bug**
get, post, put , patch and del methods throw UNIMPLEMENTED on android platform

**To Reproduce**
1. Try to call the get method on android platform
2. See error

**Expected behavior**
Methods should be implemented

**Additional context**
As a workaround you can use the request method.
Looking at the code I think this issue is also applicable to the ios platform but have not tested it.

**Comment by carlkanda** [comment] 2021-05-29 16:53
I have the same experience.

**Comment by andreastoermer** [comment] 2021-05-31 08:53
Do you have the same problem with ios?

Because I think, that my error (https://github.com/capacitor-community/http/issues/129) and yours are the same :D

**Comment by adnanomerovic** [comment] 2021-06-01 15:34
"Http.post()" is not implemented on android
I installed this lib and added  registerPlugin(Http.class); into MainAcitivity.
------------------part from package.json--------------------------------
"@capacitor-community/http": "^1.0.0",
"@capacitor/android": "^3.0.0",
"@ionic/angular": "^5.5.2",

**Comment by ultimate-tester** [comment] 2021-06-02 17:10
I just reached to the point where I have migrated my entire application to use this module due to the cookie problems that iOS currently poses. I can confirm I have the same behavior on both Android and iOS (methods not implemented on "platform").

@adnanomerovic the only thing I can see from your post is that you are still using registerPlugin, which is no longer necessary as of v3.0 (still putting it doesn't cause problems, is just unnecessary).

**Comment by ultimate-tester** [comment] 2021-06-02 17:35
I analysed the android code bundled with this plugin. I am not sure whether the HTTP method functions are left out intentionally (perhaps the author has a vision for future version) or it was a mistake. Either way, both Android and iOS still have the basic "request" method. That means that instead of using the .get or .post methods, you can use the .request method with the option "method" to indicate the desired method like so:

**Original:**
```
    const response = await Http.post({
      url: '',
      data,
      headers
    });
```
**New:**
```
    const response = await Http.request({
      method: 'POST',
      url: '',
      data,
      headers
    });
```

Hope it helps, solved my problems. If this is indeed a mistake by the author, I'm happy to submit a PR.

**Comment by phoenix503** [comment] 2021-06-07 06:42
Hii @ultimate-tester ,
I tried your method to send GET & POST Request but i am getting error like
```
CapacitorException: IO Exception
at object.cap.fromNative.result [as fromNative]
```

Did you face any kind of issue like this

I tried this method 

```
uploadFile = async () =&gt; {   
 const ret = await Http.uploadFile({     
  url: "http://localhost:3445/upload-pdf',   
     name: 'myFile',  
         filePath: 'pdf Path',
    });
    console.log('Got upload ret', ret);  };
```

**Comment by ultimate-tester** [comment] 2021-06-07 07:28
Hi @phoenix503 

Well, an IO Exception would be related to the input file you're trying to upload (I assume).
Does your app have permission to access and read that file?

**Comment by Hosam11** [comment] 2021-06-13 12:48
> Hii @ultimate-tester ,
> I tried your method to send GET & POST Request but i am getting error like
> 
> ```
> CapacitorException: IO Exception
> at object.cap.fromNative.result [as fromNative]
> ```
> 
> Did you face any kind of issue like this
> 
> I tried this method
> 
> ```
> uploadFile = async () =&gt; {   
>  const ret = await Http.uploadFile({     
>   url: "http://localhost:3445/upload-pdf',   
>      name: 'myFile',  
>          filePath: 'pdf Path',
>     });
>     console.log('Got upload ret', ret);  };
> ```

make sure you set usesCleartextTraffic to true in AndroidManifest

```
    <application
           // ...
        android:usesCleartextTraffic="true">
    </application>
```

**Comment by dargorbck** [comment] 2021-06-15 10:57
> > Hii @ultimate-tester ,
> > I tried your method to send GET & POST Request but i am getting error like
> > ```
> > CapacitorException: IO Exception
> > at object.cap.fromNative.result [as fromNative]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did you face any kind of issue like this
> > I tried this method
> > ```
> > uploadFile = async () =&gt; {   
> >  const ret = await Http.uploadFile({     
> >   url: "http://localhost:3445/upload-pdf',   
> >      name: 'myFile',  
> >          filePath: 'pdf Path',
> >     });
> >     console.log('Got upload ret', ret);  };
> > ```
> 
> make sure you set usesCleartextTraffic to true in AndroidManifest
> 
> ```
>     <application
>            // ...
>         android:usesCleartextTraffic="true">
>     </application>
> ```

Have the same problem, doing a post with an Arraybuffer as data (im using protocol buffer and has been working well on angular httpClient), and always getting the same IO Exception. I had reviewed the AndroidManifest on app folder, and i have useClearTextTraffic to true.

This is the request:

```
callbackId: "51329256"
methodName: "request"
options:
connectTimeout: 21000
data: 
ArrayBuffer(5)
headers: {Content-Type: "application/x-www-form-urlencoded", Accept: "text/plain"}
method: "POST"
readTimeout: 20000
responseType: "arraybuffer"
url: "http://192.168.4.1/prov-session"
__proto__: Object
pluginId: "Http"
```

**Comment by phoenix503** [comment] 2021-06-15 11:00
> Hi @phoenix503
> 
> Well, an IO Exception would be related to the input file you're trying to upload (I assume).
> Does your app have permission to access and read that file?

Yes i have all the permission

**Comment by mtozzi** [comment] 2021-06-19 23:46
It seems that capacitor-community/http doesn't work with capacitor 3, is that correct? Is anyone can confirm if it does?
Error: "Http.post()" is not implemented on android

**Comment by ultimate-tester** [comment] 2021-06-20 06:50
> It seems that capacitor-community/http doesn't work with capacitor 3, is that correct? Is anyone can confirm if it does? Any tips how to proceed?
> 
> Error: "Http.post()" is not implemented on android

Check my reply a few comments back on how to get it to work.

**Comment by mtozzi** [comment] 2021-06-20 11:28
Thank you @ultimate-tester , but I was already using 'request' methos insted of 'post' method before my comment, but no way to scape of '"Http.post()" is not implemented on android' error. Any further ideas?

**Comment by thomasvidas** [comment] 2021-06-25 21:21
Yeah this is my mistake, my bad! 😅

I just didn't expose these APIs publicly. You can use `Http.request()` as a workaround but I'll be sure to release a new version soon with these methods properly exposed on Android and iOS..

**Comment by dharmeshds** [comment] 2021-07-15 06:35
Even Http.request() is giving and IO exception with capacitor 3 in my ionic 5 app. Any resolution for this?

**Comment by thomasvidas** [comment] 2021-07-15 15:01
Just pushed a fix up to the `1.1.0` branch [here](https://github.com/capacitor-community/http/commit/a414232e3b9e00a28ff30187415ab96a6cdc22a9). I'll do some testing and release to npm later today

**Closed by thomasvidas** 2021-07-15 15:01 UTC
Labels: bug

**Comment by dharmeshds** [comment] 2021-07-16 00:58
Hi Thomas, I upgraded and tested but now I get an SSLHandshakeException when I place the request. It works fine with the same server certificate from the same device (trusts server certificate) when I use cordova-advanced-http plugin. What am I missing? my request is a simple GET.

**Comment by thomasvidas** [comment] 2021-07-16 03:27
Open another issue with a small reproduction of your problem. It is unrelated to this one
