### ISSUE TITLE
Unable to use setCookie() method from the native http plugin for capacitor

### ISSUE THREAD

**Issue by kasuvy** [capacitor-community/http#88] opened 2021-01-29 23:02 UTC
**Describe the bug**
The project is a Angular/Ionic based. It had the issue with the native IOS not retaining the cookies after authentication to do any subsequent requests. I tried to install the @capacitor-community/http plugin and use the Http to make requests instead of "httpClient" imported from angular. The setCookie() method is not setting the Auth cookie before performing a get/post request.

The below is the screenshot of the Request headers using the **angular httpClient** (It is having the cookie included in the request header)
![Cookie1](https://user-images.githubusercontent.com/25620183/106335611-2d826b80-625b-11eb-893c-422d3767db38.PNG)

The below is the screenshot of the Request headers using the **native http plugin** (It is missing the cookie in the request header)
![Cookie2](https://user-images.githubusercontent.com/25620183/106335612-2d826b80-625b-11eb-9ec2-9939c993c05b.PNG)

CODE SNIPPET:

async get(path, method): Promise<Observable<any>> {
      const { Http } = Plugins;
      try {
         const { Http } = Plugins;
         const cookies = await Http.getCookies({
            url: this.apiUrl("/cookie"),
         });
         console.log(cookies);
         let retValue = "";
         for (let i = 0; i < cookies.value.length; i++) {
         retValue = cookies.value[0].value;
         }
         await Http.setCookie({
            url: "http://localhost:8102/",
            key: ".ASPXAUTH",
            value: retValue,
         });
         const ret = await Http.request({
            method: method,
            url: this.apiUrl(path),
            headers: {
               "X-Fake-Header": "Max was here",
               "Content-Type": "application/json",
               withCredentials: true,
            },
         });
         console.log("Got ret", ret);
         return ret;
      } catch (e) {
         console.error(e);
      }
   }

**Comment by NKZ15** [comment] 2021-01-29 23:07
I have the same issue @mlynch @IT-MikeS @thomasvidas. setCookie is not working for me as well. Has there been any updates or any other workarounds for the iOS issue? My iOS app doesn't set cookies the first time it opens.

**Comment by thomasvidas** [comment] 2021-01-31 02:56
Duplicate of #47, closing in favor of that. This is a known bug. See #47 and [Capacitor Issue #1373](https://github.com/ionic-team/capacitor/issues/1373) for more details.

**Closed by thomasvidas** 2021-01-31 02:56 UTC
